<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => 'Идентификатор доступа',
    'Are you sure you want to delete this item?' => 'Вы уверены, что желаете удалить эти записи',
    'Auth Key' => 'Ключ доступа',
    'Born Date' => 'Дата рождения',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создать',
    'Data' => 'Данные',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Home' => 'Домой',
    'ID' => 'Идентификатор',
    'Lastname' => 'Отчество',
    'Login' => 'Логин',
    'Name' => 'Имя',
    'Not entered user identifier' => 'Не указан идентификатор пользователя',
    'Password' => 'Пароль',
    'Phone Number' => 'Номер телефона',
    'Registered' => 'Зарегистрирован',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Surname' => 'Фамилия',
    'Text is not sended' => 'Текст не отправлен',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить',
    'User ID' => 'Идентификатор пользователя',
    'User Information' => 'Информация о пользователе',
    'User Infos' => 'Информация о пользователях',
    'Users' => 'Пользователи',
];
