<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Log Out ({login})' => 'Выйти ({login})',
    'Text is not sended' => '@@Текст не отправлен@@',
    'User Information' => '@@Информация о пользователе@@',
    'About' => 'О сайте',
    'Access Token' => 'Идентификатор доступа',
    'Are you sure you want to delete this item?' => 'Вы уверены, что желаете удалить эти записи',
    'Auth Key' => 'Ключ доступа',
    'Bad email format' => 'Неверный формат электронной почты',
    'Born Date' => 'Дата рождения',
    'Command' => 'Команда',
    'Contact' => 'Контакт',
    'Contact list' => 'Список контактов',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создать',
    'Data' => 'Данные',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'E-mail' => 'Электронная почта',
    'Fix' => 'Фиксировать',
    'From' => 'От',
    'Home' => 'Домой',
    'ID' => 'Идентификатор',
    'Incorrect login or password.' => 'Неверное имя пользователя или пароль.',
    'Lastname' => 'Отчество',
    'Log In' => 'Войти',
    'Message' => 'Сообщение',
    'Name' => 'Имя',
    'Not entered user identifier' => 'Не указан идентификатор пользователя',
    'Password' => 'Пароль',
    'Passwords not equal' => 'Пароли не совпадают',
    'Phone Number' => 'Номер телефона',
    'Register' => 'Зарегистрироваться',
    'Registered' => 'Зарегистрирован',
    'Registration' => 'Регистрация',
    'Repeat password' => 'Повторить пароль',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Sended from' => 'Отправитель',
    'Sended to' => 'Получатель',
    'Sorry! Can not create new user. It\'s my error.' => 'Извините! Не удается создать пользователя. Ошибка на сервере',
    'Surname' => 'Фамилия',
    'The Talk' => 'Talk',
    'To' => 'К',
    'Unexpected exception' => 'Непредвиденная ошибка',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить',
    'User ID' => 'Идентификатор пользователя',
    'User Infos' => 'Информация о пользователях',
    'User with that login "{login}" are registered' => 'Пользователь с таким именем "{login}" уже зарегистрирован',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
    'Welcome to the Talk' => 'Добро пожаловать в Talk',
    'Welcome to the Talk messenger' => 'Добро пожаловать в интерактивный мессенджер Talk',
];
